/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/generate-types.mjs. Do not edit by hand.
 * Source of truth: the JSON Schemas in src/schemas.
 */

/**
 * CMS-neutral source object for Teacher and Family experiences rendered from one governed lesson. Version 1.2 normalizes quiz answers and puzzle solutions into typed objects so Git-based CMS editors do not need polymorphic fields.
 */
export interface SundaySchoolCanonicalLessonContent {
  schema_version: "1.2.1";
  lesson_id: string;
  content_version: string;
  status: "vertical_slice_draft" | "in_review" | "approved" | "scheduled" | "published" | "retired";
  curriculum: Curriculum;
  core: Core;
  learning: Learning;
  teacher: Teacher;
  family: Family;
  engagement: Engagement;
  accessibility: Accessibility;
  safeguarding: Safeguarding;
  editorial: Editorial;
}
export interface Curriculum {
  segment: "Kids" | "Youths" | "Teens";
  age_range: "4-8" | "9-12" | "13-17";
  cycle_id: string;
  cycle_name: string;
  sequence: number;
  unit_type: "Core" | "Synthesis" | "Flex";
  scheduling_priority?: "Required" | "Recommended" | "Optional";
  title: string;
  annual_anchor?: string;
  thematic_unit?: string;
}
export interface Core {
  big_idea: string;
  /**
   * @minItems 1
   */
  passages: [Passage, ...Passage[]];
  metanarrative_position: string;
  biblical_genre: string;
  /**
   * @minItems 2
   */
  claims: [Claim, Claim, ...Claim[]];
  doctrine_tags: string[];
  formation_tags: string[];
  interpretation_skill?: string;
  key_terms?: string[];
}
export interface Passage {
  reference: string;
  role: "primary" | "supporting" | "context" | "comparison";
  reading_note?: string;
}
export interface Claim {
  claim_id: string;
  statement: string;
  classification:
    | "explicit_text"
    | "canonical_synthesis"
    | "strong_inference"
    | "framework_position"
    | "disputed"
    | "historical_context"
    | "prudential_judgment";
  /**
   * @minItems 1
   */
  evidence_refs: [string, ...string[]];
  confidence: "High" | "Medium" | "Low";
  review_status: "draft" | "review_required" | "approved";
  credible_alternative?: string;
  interpretive_hinge?: string;
  prohibited_overstatement?: string;
}
export interface Learning {
  foundation_objective: string;
  extension_objective: string;
  /**
   * @minItems 1
   */
  know: [string, ...string[]];
  /**
   * @minItems 1
   */
  understand: [string, ...string[]];
  /**
   * @minItems 1
   */
  practise: [string, ...string[]];
  /**
   * @minItems 1
   */
  become: [string, ...string[]];
  success_evidence?: string[];
}
export interface Teacher {
  default_profile: "essential" | "standard" | "extended";
  preparation_minutes: number;
  zero_prep_card: {
    objective: string;
    read: string;
    opening: string;
    /**
     * @minItems 2
     */
    say: [string, string, ...string[]];
    /**
     * @minItems 2
     */
    ask: [string, string, ...string[]];
    do: string;
    close: string;
    materials: string[];
  };
  preparation: {
    passage_context: string;
    /**
     * @minItems 2
     */
    text_observations: [string, string, ...string[]];
    /**
     * @minItems 1
     */
    interpretation_notes: [string, ...string[]];
    /**
     * @minItems 1
     */
    theological_guardrails: [string, ...string[]];
    likely_questions: Question[];
  };
  /**
   * @minItems 3
   */
  discussion_questions: [Question, Question, Question, ...Question[]];
  /**
   * @minItems 1
   */
  activities: [Activity, ...Activity[]];
  closing: {
    memory_reference: string;
    prayer_prompt: string;
    take_home_line: string;
  };
  printable_refs?: string[];
  delivery_profiles: {
    essential: DeliveryProfile;
    standard: DeliveryProfile;
    extended: DeliveryProfile;
  };
}
export interface Question {
  question_id?: string;
  question: string;
  purpose: string;
  foundation_prompt?: string;
  extension_prompt?: string;
}
export interface Activity {
  activity_id: string;
  title: string;
  duration_minutes: number;
  materials: string[];
  /**
   * @minItems 1
   */
  steps: [string, ...string[]];
  learning_link: string;
  low_resource_alternative?: string;
}
export interface DeliveryProfile {
  label: string;
  duration_minutes: 25 | 35 | 45;
  use_case: string;
  /**
   * @minItems 4
   */
  outline: [OutlineStep, OutlineStep, OutlineStep, OutlineStep, ...OutlineStep[]];
}
export interface OutlineStep {
  step_id: string;
  minutes: number;
  label: string;
  instructions: string;
  question_refs?: string[];
  activity_refs?: string[];
  resource_refs?: string[];
}
export interface Family {
  duration_minutes: 15;
  title: string;
  parent_intro: string;
  /**
   * @minItems 5
   * @maxItems 5
   */
  flow: [FamilyFlowStep, FamilyFlowStep, FamilyFlowStep, FamilyFlowStep, FamilyFlowStep];
  /**
   * @minItems 2
   */
  questions: [string, string, ...string[]];
  interactive: {
    type: "quiz" | "puzzle" | "discussion" | "movement" | "creative" | "audit";
    title: string;
    instructions: string;
  };
  weekly_action: string;
  prayer: string;
  parent_note: string;
}
export interface FamilyFlowStep {
  duration_minutes: number;
  type: "connect" | "read" | "understand" | "play" | "respond";
  instructions: string;
}
export interface Engagement {
  /**
   * @minItems 3
   */
  quiz: [QuizQuestion, QuizQuestion, QuizQuestion, ...QuizQuestion[]];
  puzzle: {
    type: "sequence" | "matching" | "sort" | "word_scramble" | "case_grid";
    title: string;
    instructions: string;
    items?: string[];
    solution: PuzzleSolution;
    choices?: string[];
  };
  printables: {
    resource_id: string;
    title: string;
    purpose: string;
    format: "A4" | "US Letter" | "cards" | "worksheet" | "none";
    status: "placeholder" | "content_source_draft" | "ready";
  }[];
}
export interface QuizQuestion {
  question_id: string;
  question: string;
  type: "multiple_choice" | "true_false" | "sequence" | "scenario" | "short_answer";
  options?: string[];
  answer: QuizAnswer;
  explanation: string;
}
export interface QuizAnswer {
  kind: "text" | "boolean" | "ordered_list";
  text?: string;
  boolean?: boolean;
  items?: string[];
}
export interface PuzzleSolution {
  kind: "text" | "ordered_list" | "pairs" | "groups";
  text?: string;
  items?: string[];
  pairs?: PuzzlePair[];
  groups?: PuzzleGroup[];
}
export interface PuzzlePair {
  prompt: string;
  answer: string;
}
export interface PuzzleGroup {
  label: string;
  items: string[];
}
export interface Accessibility {
  reading_level: string;
  plain_language_rule: string;
  neurodiversity_supports: string[];
  sensory_notes: string[];
  non_reader_support: string[];
}
export interface Safeguarding {
  sensitivity_tags: string[];
  do_not_ask: string[];
  teacher_response: string;
  escalation_required: boolean;
  escalation_note?: string;
}
export interface Editorial {
  /**
   * @minItems 1
   */
  source_provenance: [string, ...string[]];
  decision_register_refs: string[];
  review_flags: string[];
  review_state: {
    exegetical: "not_started" | "in_review" | "approved" | "not_required";
    developmental: "not_started" | "in_review" | "approved" | "not_required";
    pastoral: "not_started" | "in_review" | "approved" | "not_required" | "deferred_owner_managed";
    copy: "not_started" | "in_review" | "approved";
  };
  scripture_text_policy: string;
  editor_notes?: string[];
}
