/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/generate-types.mjs. Do not edit by hand.
 * Source of truth: the JSON Schemas in src/schemas.
 */

export interface PrintableResource {
  resource_id: string;
  lesson_id: string;
  title: string;
  purpose: string;
  format: "A4" | "US Letter" | "cards" | "worksheet" | "none";
  status: "placeholder" | "content_source_draft" | "ready";
  body_markdown: string;
}
