/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/generate-types.mjs. Do not edit by hand.
 * Source of truth: the JSON Schemas in src/schemas.
 */

export type ScheduleEntry = {
  [k: string]: unknown | undefined;
} & {
  schedule_id: string;
  date: string;
  segment: "Kids" | "Youths" | "Teens";
  entry_type: "lesson" | "break" | "special";
  lesson_id?: string;
  title_override?: string;
  message?: string;
  status: "draft" | "approved" | "cancelled";
  notes?: string;
};
