/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/generate-types.mjs. Do not edit by hand.
 * Source of truth: the JSON Schemas in src/schemas.
 */

export interface SiteSettings {
  site_name: string;
  timezone: "Pacific/Auckland";
  default_teacher_profile: "essential" | "standard" | "extended";
  family_duration_minutes: 15;
  public_teacher_routes: boolean;
  show_upcoming_lessons: boolean;
}
