// Generates TypeScript types from the JSON Schemas so runtime types cannot
// drift from the content contract. Output is committed; re-run after any
// schema change (schema changes themselves require an ADR + migration).
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { compile } from 'json-schema-to-typescript';

const root = process.cwd();
const outDir = path.join(root, 'src/types');
fs.mkdirSync(outDir, { recursive: true });

const targets = [
  { schema: 'src/schemas/lesson.schema.json', name: 'LessonContent', out: 'lesson.generated.ts' },
  { schema: 'src/schemas/resource.schema.json', name: 'PrintableResource', out: 'resource.generated.ts' },
  { schema: 'src/schemas/schedule-entry.schema.json', name: 'ScheduleEntry', out: 'schedule-entry.generated.ts' },
  { schema: 'src/schemas/site-settings.schema.json', name: 'SiteSettings', out: 'site-settings.generated.ts' },
];

const banner = `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/generate-types.mjs. Do not edit by hand.
 * Source of truth: the JSON Schemas in src/schemas.
 */
`;

for (const target of targets) {
  const schema = JSON.parse(fs.readFileSync(path.join(root, target.schema), 'utf8'));
  const ts = await compile(schema, target.name, {
    bannerComment: banner,
    additionalProperties: false,
    strictIndexSignatures: true,
  });
  fs.writeFileSync(path.join(outDir, target.out), ts);
  console.log(`Generated src/types/${target.out} from ${target.schema}`);
}
